In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('train_knn.csv', usecols=['Age','Pclass','Fare','Survived'])

In [3]:
df

     Survived  Pclass   Age     Fare
0           0       3  22.0   7.2500
1           1       1  38.0  71.2833
2           1       3  26.0   7.9250
3           1       1  35.0  53.1000
4           0       3  35.0   8.0500
..        ...     ...   ...      ...
886         0       2  27.0  13.0000
887         1       1  19.0  30.0000
888         0       3   NaN  23.4500
889         1       1  26.0  30.0000
890         0       3  32.0   7.7500

[891 rows x 4 columns]

In [4]:

df.isnull().mean() * 100

Survived     0.00000
Pclass       0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [5]:
X = df.drop(columns=['Survived'])
Y = df['Survived']

In [6]:
X.sample(5)

     Pclass   Age     Fare
688       3  18.0   7.7958
674       2   NaN   0.0000
243       3  22.0   7.1250
26        3   NaN   7.2250
487       1  58.0  29.7000

Y

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=2)

In [10]:

X_train.head()

     Pclass   Age     Fare
30        1  40.0  27.7208
10        3   4.0  16.7000
873       3  47.0   9.0000
182       3   9.0  31.3875
876       3  20.0   9.8458

# KNN Imputer

In [12]:
knn = KNNImputer(n_neighbors=5, weights='distance')
X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.transform(X_test)

array([[  1.        ,  40.        ,  27.7208    ],
       [  3.        ,   4.        ,  16.7       ],
       [  3.        ,  47.        ,   9.        ],
       ...,
       [  1.        ,  71.        ,  49.5042    ],
       [  1.        ,  29.53007554, 221.7792    ],
       [  1.        ,  49.2759266 ,  25.925     ]], shape=(712, 3))

In [32]:
lr = LogisticRegression()
lr.fit(X_train_trf, y_train)
y_pred = lr.predict(X_test_trf)
res=accuracy_score(y_test, y_pred)

In [33]:
(res*100)

70.39106145251397

# Comparision with Simple Imputer --> mean

In [34]:
si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [29]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978