# working with json

In [1]:
import pandas as pd

In [5]:
df = pd.read_json('https://microsoftedge.github.io/Demos/json-dummy-data/64KB.json)

In [51]:
df

Empty DataFrame
Columns: []
Index: []

# working with MySQL

In [52]:
!pip install mysql-connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector in c:\users\tarun gupta\appdata\roaming\python\python311\site-packages (2.2.9)

In [53]:
!pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\tarun gupta\appdata\roaming\python\python311\site-packages (9.7.0)

In [56]:
import mysql.connector

In [55]:
conn = mysql.connector.connect(
host="127.0.0.1",
database = 'world',
    password = ''
   )

ProgrammingError: 1045 (28000): Access denied for user 'ODBC'@'localhost' (using password: NO)

In [ ]:
conn

In [ ]:
import pandas as pd
df = pd.read_sql_query('select * from city' , conn)

In [13]:
df

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]

In [14]:
df.shape

(4079, 5)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4079 entries, 0 to 4078
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           4079 non-null   int64
 1   Name         4079 non-null   object
 2   CountryCode  4079 non-null   object
 3   District     4079 non-null   object
 4   Population   4079 non-null   int64
dtypes: int64(2), object(3)
memory usage: 159.5+ KB

# working with API

In [16]:
!python -m pip install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.33.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\tarun gupta\appdata\roaming\python\python311\site-packages (from requests) (1.26.20)
Requirement already satisfied: certifi>=2023.5.7 in c:\programdata\anaconda3\lib\site-packages (from requests) (2026.5.20)

In [33]:
import requests

url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNjQ1YzNiYjBlYjdjODViM2NjNTIxYzQyNDU3YWI3YyIsIm5iZiI6MTc4MDg0NTIzNC40NzgwMDAyLCJzdWIiOiI2YTI1OGFiMjE4OGE1OTMyOTQ2MzEyZDEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.T9aDmUvVlFXfwILgapG5v-lbqloEJeCLAltAZ0xyFsw"
}

response = requests.get(url, headers=headers)

print(response.json())

{'page': 1, 'results': [{'adult': False, 'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg', 'genre_ids': [12, 16, 10751, 14], 'id': 1007757, 'title': 'Swapped', 'original_language': 'en', 'original_title': 'Swapped', 'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.', 'popularity': 216.3932, 'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg', 'release_date': '2026-05-01', 'softcore': False, 'video': False, 'vote_average': 8.979, 'vote_count': 1599}, {'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'title': 'The Shawshank Redemption', 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 76.3536, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'softcore': False, 'video': False, 'vote_average': 8.722, 'vote_count': 30500}, {'adult': False, 'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg', 'genre_ids': [18, 80], 'id': 238, 'title': 'The Godfather', 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 44.8929, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'softcore': False, 'video': False, 'vote_average': 8.687, 'vote_count': 23000}, {'adult': False, 'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg', 'genre_ids': [878, 12], 'id': 687163, 'title': 'Project Hail Mary', 'original_language': 'en', 'original_title': 'Project Hail Mary', 'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.', 'popularity': 251.0803, 'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg', 'release_date': '2026-03-15', 'softcore': False, 'video': False, 'vote_average': 8.66, 'vote_count': 4714}, {'adult': False, 'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 'genre_ids': [18, 80], 'id': 240, 'title': 'The Godfather Part II', 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 31.4238, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'softcore': False, 'video': False, 'vote_average': 8.572, 'vote_count': 13945}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'title': "Schindler's List", 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 24.4928, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'softcore': False, 'video': False, 'vote_average': 8.569, 'vote_count': 17491}, {'adult': False, 'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg', 'genre_ids': [18], 'id': 389, 'title': '12 Angry Men', 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 24.5916, 'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg', 'release_date': '1957-04-10', 'softcore': False, 'video': False, 'vote_average': 8.562, 'vote_count': 10015}, {'adult': False, 'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg', 'genre_ids': [18, 9648], 'id': 1330021, 'title': 'Remarkably Bright Creatures', 'original_language': 'en', 'original_title': 'Remarkably Bright Creatures', 'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.', 'popularity': 49.0425, 'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg', 'release_date': '2026-05-07', 'softcore': False, 'video': False, 'vote_average': 8.545, 'vote_count': 556}, {'adult': False, 'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'title': 'Spirited Away', 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 35.1311, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'softcore': False, 'video': False, 'vote_average': 8.535, 'vote_count': 18372}, {'adult': False, 'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg', 'genre_ids': [28, 80, 53], 'id': 155, 'title': 'The Dark Knight', 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 40.1315, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'softcore': False, 'video': False, 'vote_average': 8.531, 'vote_count': 35852}, {'adult': False, 'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'title': 'Dilwale Dulhania Le Jayenge', 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 18.3882, 'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg', 'release_date': '1995-10-20', 'softcore': False, 'video': False, 'vote_average': 8.5, 'vote_count': 4591}, {'adult': False, 'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'title': 'The Green Mile', 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 28.0257, 'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg', 'release_date': '1999-12-10', 'softcore': False, 'video': False, 'vote_average': 8.507, 'vote_count': 19297}, {'adult': False, 'backdrop_path': '/ctiw6FZK4N36LmkjSklWEbuvlq9.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'title': 'The Lord of the Rings: The Return of the King', 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 43.5172, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'softcore': False, 'video': False, 'vote_average': 8.499, 'vote_count': 26606}, {'adult': False, 'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'title': 'Parasite', 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 35.0029, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'softcore': False, 'video': False, 'vote_average': 8.494, 'vote_count': 20687}, {'adult': False, 'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg', 'genre_ids': [35, 10749], 'id': 1181678, 'title': '¿Quieres ser mi hijo?', 'original_language': 'en', 'original_title': '¿Quieres ser mi hijo?', 'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.', 'popularity': 12.5156, 'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg', 'release_date': '2023-09-21', 'softcore': False, 'video': False, 'vote_average': 8.493, 'vote_count': 354}, {'adult': False, 'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 'genre_ids': [53, 80, 35], 'id': 680, 'title': 'Pulp Fiction', 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 33.8069, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'softcore': False, 'video': False, 'vote_average': 8.483, 'vote_count': 30248}, {'adult': False, 'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'title': 'Your Name.', 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 31.714, 'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg', 'release_date': '2016-08-26', 'softcore': False, 'video': False, 'vote_average': 8.481, 'vote_count': 12592}, {'adult': False, 'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'title': 'Interstellar', 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 72.0966, 'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg', 'release_date': '2014-11-05', 'softcore': False, 'video': False, 'vote_average': 8.5, 'vote_count': 39930}, {'adult': False, 'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg', 'genre_ids': [37], 'id': 429, 'title': 'The Good, the Bad and the Ugly', 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 25.227, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-23', 'softcore': False, 'video': False, 'vote_average': 8.468, 'vote_count': 9668}, {'adult': False, 'backdrop_path': '/66Kn4XWhkuPkJxOJyPEx4U2CUfN.jpg', 'genre_ids': [35, 18, 10749], 'id': 13, 'title': 'Forrest Gump', 'original_language': 'en', 'original_title': 'Forrest Gump', 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'popularity': 28.6181, 'poster_path': '/Cw4hIUIAmSYfK9QfaUW5igp9La.jpg', 'release_date': '1994-06-23', 'softcore': False, 'video': False, 'vote_average': 8.465, 'vote_count': 29799}], 'total_pages': 546, 'total_results': 10908}

In [45]:
df = pd.DataFrame(response.json()['results'])[['id','title','release_date','original_language','overview','popularity']]

KeyError: 'results'

In [32]:
df

,id,title,release_date,original_language,overview,popularity
0,1007757,Swapped,2026-05-01,en,"A small woodland creature and a majestic bird,...",216.3932
1,278,The Shawshank Redemption,1994-09-23,en,Imprisoned in the 1940s for the double murder ...,76.3536
2,238,The Godfather,1972-03-14,en,"Spanning the years 1945 to 1955, a chronicle o...",44.8929
3,687163,Project Hail Mary,2026-03-15,en,Science teacher Ryland Grace wakes up on a spa...,251.0803
4,240,The Godfather Part II,1974-12-20,en,In the continuing saga of the Corleone crime f...,31.4238
5,424,Schindler's List,1993-12-15,en,The true story of how businessman Oskar Schind...,24.4928
6,389,12 Angry Men,1957-04-10,en,The defense and the prosecution have rested an...,24.5916
7,1330021,Remarkably Bright Creatures,2026-05-07,en,Through unlikely bonds formed during night shi...,49.0425
8,129,Spirited Away,2001-07-20,ja,"A young girl, Chihiro, becomes trapped in a st...",35.1311
9,155,The Dark Knight,2008-07-16,en,Batman raises the stakes in his war on crime. ...,40.1315
10,19404,Dilwale Dulhania Le Jayenge,1995-10-20,hi,"Raj is a rich, carefree, happy-go-lucky second...",18.3882
11,497,The Green Mile,1999-12-10,en,A supernatural tale set on death row in a Sout...,28.0257
12,122,The Lord of the Rings: The Return of the King,2003-12-17,en,As armies mass for a final battle that will de...,43.5172
13,496243,Parasite,2019-05-30,ko,"All unemployed, Ki-taek's family takes peculia...",35.0029
14,1181678,¿Quieres ser mi hijo?,2023-09-21,en,"Lu, a conformist woman in her forties, learns ...",12.5156
15,680,Pulp Fiction,1994-09-10,en,"A burger-loving hit man, his philosophical par...",33.8069
16,372058,Your Name.,2016-08-26,ja,High schoolers Mitsuha and Taki are complete s...,31.7140
17,157336,Interstellar,2014-11-05,en,The adventures of a group of explorers who mak...,72.0966
18,429,"The Good, the Bad and the Ugly",1966-12-23,it,While the Civil War rages on between the Union...,25.2270
19,13,Forrest Gump,1994-06-23,en,A man with a low IQ has accomplished great thi...,28.6181

In [36]:
df.shape

(20, 6)

In [37]:
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwNjQ1YzNiYjBlYjdjODViM2NjNTIxYzQyNDU3YWI3YyIsIm5iZiI6MTc4MDg0NTIzNC40NzgwMDAyLCJzdWIiOiI2YTI1OGFiMjE4OGE1OTMyOTQ2MzEyZDEiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.T9aDmUvVlFXfwILgapG5v-lbqloEJeCLAltAZ0xyFsw"
}

In [42]:
dfs = []

In [44]:
for i in range(1,547):
    response = requests.get(f'https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}', headers=headers)
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','release_date','original_language','overview','popularity']]
    dfs.append(temp_df)

KeyError: 'results'

In [ ]:
print("x")

In [ ]:
df = pd.concat(dfs,ignore_index = True)

In [ ]:
df