In [1]:
import numpy as np
import pandas as pd

In [2]:

df = pd.read_csv('cars.csv')

In [3]:

df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

# 1. one-hot encoding using pandas

In [5]:
df_encoded_pandas = pd.get_dummies(df, columns=['fuel','owner'])

In [6]:
df_encoded_pandas.info()

<class 'pandas.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   brand                       8128 non-null   str
 1   km_driven                   8128 non-null   int64
 2   selling_price               8128 non-null   int64
 3   fuel_CNG                    8128 non-null   bool
 4   fuel_Diesel                 8128 non-null   bool
 5   fuel_LPG                    8128 non-null   bool
 6   fuel_Petrol                 8128 non-null   bool
 7   owner_First Owner           8128 non-null   bool
 8   owner_Fourth & Above Owner  8128 non-null   bool
 9   owner_Second Owner          8128 non-null   bool
 10  owner_Test Drive Car        8128 non-null   bool
 11  owner_Third Owner           8128 non-null   bool
dtypes: bool(9), int64(2), str(1)
memory usage: 262.1 KB

# 2. N-1 One-hot encoding to avoid multicollinearity

In [7]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# 3. One-Hot Encoding using Scikit-Learn

In [8]:

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=42)

In [9]:

from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=int)

In [11]:
ohe.fit(X_train[['fuel','owner']])

OneHotEncoder(drop='first', dtype=<class 'int'>, sparse_output=False)

In [12]:
X_train_new = ohe.transform(X_train[['fuel', 'owner']])

In [13]:
X_train_new

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0]], shape=(6502, 7))

In [14]:
X_test_new = ohe.transform(X_test[['fuel', 'owner']])

In [15]:
X_train_new = pd.DataFrame(X_train_new, columns=ohe.get_feature_names_out(['fuel', 'owner']), index=X_train.index)
print(X_train_new)

      fuel_Diesel  fuel_LPG  fuel_Petrol  owner_Fourth & Above Owner  \
6518            0         0            1                           0
6144            0         0            1                           0
6381            1         0            0                           1
438             1         0            0                           0
5939            0         0            1                           0
...           ...       ...          ...                         ...
5226            1         0            0                           0
5390            1         0            0                           0
860             0         0            1                           0
7603            1         0            0                           0
7270            0         0            1                           0

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner
6518                   0                     0                  0
6144                   1                     0                  0
6381                   0                     0                  0
438                    1                     0                  0
5939                   0                     0                  0
...                  ...                   ...                ...
5226                   0                     0                  0
5390                   1                     0                  0
860                    0                     0                  0
7603                   0                     0                  0
7270                   1                     0                  0

[6502 rows x 7 columns]

In [16]:
X_test_new = pd.DataFrame(X_test_new, columns=ohe.get_feature_names_out(['fuel', 'owner']), index= X_test.index)
print(X_test_new)

      fuel_Diesel  fuel_LPG  fuel_Petrol  owner_Fourth & Above Owner  \
1971            0         0            1                           0
4664            1         0            0                           0
5448            1         0            0                           0
3333            0         0            1                           0
2316            1         0            0                           0
...           ...       ...          ...                         ...
1149            1         0            0                           0
5002            0         0            1                           0
6008            0         0            1                           0
2283            0         0            1                           0
5428            0         0            1                           0

      owner_Second Owner  owner_Test Drive Car  owner_Third Owner
1971                   0                     0                  1
4664                   0                     0                  0
5448                   0                     0                  0
3333                   1                     0                  0
2316                   1                     0                  0
...                  ...                   ...                ...
1149                   0                     0                  0
5002                   0                     0                  0
6008                   0                     0                  0
2283                   0                     0                  0
5428                   1                     0                  0

[1626 rows x 7 columns]

In [17]:
# why i am passing index parameter here think for this 
# if i don't pass it then index in that new dataframe from 0 to ... and in orignal x_train index are we getting grom X_train so when we concat it horizontally so it will combine based on index and their index order doesn't match so it willc create rows with naN values and redudant data

In [18]:
import numpy as np

In [19]:
X_train.shape , X_test.shape , df.shape

((6502, 4), (1626, 4), (8128, 5))

In [20]:
X_train_new.shape , X_test_new.shape , df.shape

((6502, 7), (1626, 7), (8128, 5))

In [21]:
X_train_new.head()

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6518,0,0,1,0,0,0,0
6144,0,0,1,0,1,0,0
6381,1,0,0,1,0,0,0
438,1,0,0,0,1,0,0
5939,0,0,1,0,0,0,0

In [22]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [23]:
X_train_combined = pd.concat(
    [X_train[['brand', 'km_driven']], X_train_new],
    axis=1
)

In [24]:
X_train_combined

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
6518,Tata,2560,0,0,1,0,0,0,0
6144,Honda,80000,0,0,1,0,1,0,0
6381,Hyundai,150000,1,0,0,1,0,0,0
438,Maruti,120000,1,0,0,0,1,0,0
5939,Maruti,25000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...
5226,Mahindra,120000,1,0,0,0,0,0,0
5390,Maruti,80000,1,0,0,0,1,0,0
860,Hyundai,35000,0,0,1,0,0,0,0
7603,Maruti,27000,1,0,0,0,0,0,0
7270,Maruti,70000,0,0,1,0,1,0,0

In [25]:
X_test_combined = pd.concat(
    [X_test[['brand', 'km_driven']], X_test_new],
    axis=1
)

In [26]:
X_test_combined

,brand,km_driven,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
1971,Honda,110000,0,0,1,0,0,0,1
4664,Tata,291977,1,0,0,0,0,0,0
5448,Maruti,70000,1,0,0,0,0,0,0
3333,Honda,120000,0,0,1,0,1,0,0
2316,Maruti,69000,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
1149,BMW,8500,1,0,0,0,0,0,0
5002,Maruti,40000,0,0,1,0,0,0,0
6008,Hyundai,54043,0,0,1,0,0,0,0
2283,Tata,70000,0,0,1,0,0,0,0
5428,Chevrolet,110000,0,0,1,0,1,0,0

In [27]:
# 4. One -Hot Encoding for column having high cardinality

In [29]:

counts = df['brand'].value_counts()

In [30]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [31]:
df['brand'].nunique()

32

In [34]:
type(counts)

pandas.Series

In [32]:
threshold = 100

In [41]:

repl = counts[counts <= threshold].index

In [43]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='str', name='brand')

In [48]:

pd.get_dummies(df['brand'].replace(repl, 'others')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
4104,False,False,False,False,False,False,True,False,False,False,False,False,False
3620,False,False,False,False,False,False,True,False,False,False,False,False,False
1015,False,False,False,False,False,False,False,False,False,False,False,False,True
6861,False,False,False,False,False,True,False,False,False,False,False,False,False
4627,False,False,False,False,False,False,False,False,False,False,True,False,False